@echo on
cd /d "C:\Users\trive\Desktop\Distributed file system\Distributed-File-Storage-System-master"
call C:\Users\trive\venv\Scripts\activate
echo Cleaning old protobuf files...
del /Q fileService_pb2.py fileService_pb2_grpc.py heartbeat_pb2.py heartbeat_pb2_grpc.py fluffy_pb2.py fluffy_pb2_grpc.py
echo Generating fileService...
python -m grpc_tools.protoc -I proto --python_out=. --grpc_python_out=. proto/fileService.proto
echo Generating heartbeat...
python -m grpc_tools.protoc -I proto --python_out=. --grpc_python_out=. proto/heartbeat.proto
echo Generating fluffy...
python -m grpc_tools.protoc -I proto --python_out=. --grpc_python_out=. proto/fluffy.proto