@echo off
cd /d "C:\Users\trive\Desktop\Distributed file system\Distributed-File-Storage-System-master"

:: Activate virtual environment
call C:\Users\trive\venv\Scripts\activate

echo Starting Redis...
start cmd /k "C:\Users\trive\Desktop\Redis-x64-3.0.504\redis-server.exe > redis.log 2>&1"
echo Starting MongoDB...
start cmd /k "C:\Users\trive\Desktop\mongodb-windows-x86_64-8.0.6\mongodb-win32-x86_64-windows-8.0.6\bin\mongod.exe --dbpath C:\Users\trive\Desktop\mongodb-data > mongodb.log 2>&1"
echo Building Protobuf files...
call build_pb.bat > build_pb.log 2>&1
echo Starting Supernode...
start cmd /k "python superNode.py > supernode.log 2>&1"
echo Waiting for Supernode to start...
timeout /t 10
echo Starting Server (Node one)...
start cmd /k "python server.py --node one > server_one.log 2>&1"
echo Starting Server (Node two)...
start cmd /k "python server.py --node two > server_two.log 2>&1"
echo Starting Server (Node three)...
start cmd /k "python server.py --node three > server_three.log 2>&1"
echo Starting Server (Node four)...
start cmd /k "python server.py --node four > server_four.log 2>&1"
echo Starting Server (Node five)...
start cmd /k "python server.py --node five > server_five.log 2>&1"
echo Starting Server (Node six)...
start cmd /k "python server.py --node six > server_six.log 2>&1"
echo Waiting for nodes to elect a leader...
timeout /t 60
echo Starting Client...
start cmd /k "python client.py > client.log 2>&1"
echo All components started. Check logs for details.